# Config file for automatic testing at travis-ci.org

language: python
dist: xenial
python:
  - 3.7
  - 3.8
  - 3.9

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements_dev.txt

# Command to run tests, e.g. python setup.py test
script:
  - mypy --config-file mypy.ini nelson_siegel_svensson tests
  - flake8 nelson_siegel_svensson tests
  - python setup.py test