# Config file for automatic testing at travis-ci.com

language: python
dist: focal
python:
  - 3.7
  - 3.8
  - 3.9-dev # proper 3.9 is not yet available

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements_dev.txt

# Command to run tests, e.g. python setup.py test
script:
  - mypy --config-file mypy.ini nelson_siegel_svensson tests
  - flake8 nelson_siegel_svensson tests
  - python -m unittest discover tests -v